Repository Selleo/mentingo, pull requests merged in 2024-11, with the labels that each got.

#203 feat: blocking editing of lessons and questions with answers
  apps/api/src/lessons/adminLessonItems.service.ts
  apps/api/src/lessons/adminLessons.service.ts
  apps/api/src/lessons/api/lessons.controller.ts
  apps/api/src/lessons/lessonItems.type.ts
  apps/api/src/lessons/lessons.module.ts
  apps/api/src/lessons/repositories/adminLessonItems.repository.ts
  apps/api/src/lessons/repositories/adminLessons.repository.ts
  apps/api/src/lessons/schemas/lessonItem.schema.ts
Labels: review me :eyes:

#205 fix: LC-313 logout fix
  apps/web/app/api/api-client.ts
  apps/web/app/api/mutations/useLogoutUser.ts
  apps/web/app/api/queryClient.ts
  apps/web/app/utils/mocks/handlers/auth.ts
  apps/web/app/utils/mocks/handlers/course.ts
Labels: review me :eyes:

#208 fix: error handling in queryClient retry function
  apps/web/app/api/queryClient.ts
Labels: review me :eyes:

#207 style: improve visibility and update conditional classes for TextBlank component
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/TextBlank.tsx
Labels: review me :eyes:

#209 feat: disable dnd on completed quiz
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DraggableWord.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
Labels: review me :eyes:

#213 feat: Add fill in the blanks word template option to EditorToolbar
  apps/web/app/components/RichText/toolbar/EditorToolbar.tsx
Labels: review me :eyes:

#210 feat: Show correct answer as a full text with bold keywords
  apps/api/src/courses/courses.service.ts
  apps/api/src/lessons/api/lessons.controller.ts
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/lessons/schemas/lesson.schema.ts
  apps/api/src/lessons/schemas/lesson.types.ts
  apps/api/src/lessons/schemas/lessonFileType.ts
  apps/api/src/lessons/schemas/lessonItem.schema.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/queries/admin/useQuestionOptions.ts
  apps/web/app/components/CourseProgress.tsx
  apps/web/app/modules/Admin/LessonItems/QuestionItem.tsx
  apps/web/app/modules/Admin/LessonItems/question/AnswerOptions.tsx
  apps/web/app/modules/Admin/LessonItems/question/QuestionField.tsx
  apps/web/app/modules/Courses/CourseView/LessonCard.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/FillInTheBlanks.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/Question.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswer.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOption.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOptionQuiz.tsx
  apps/web/app/modules/Courses/Lesson/Overview.tsx
  apps/web/app/modules/Dashboard/Courses/StudentCoursesCarousel.tsx
Labels: review me :eyes:

#214 feat: implement Gravatar component for user avatars
  apps/web/app/components/Gravatar.tsx
  apps/web/app/modules/Dashboard/DashboardNavigation/UserProfile.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: review me :eyes:

#223 refactor: Quiz and dashboard appearance adjustments
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/SelectAnswer/SelectAnswerOptionQuiz.tsx
  apps/web/app/modules/Dashboard/Courses/CardCourseList.tsx
  apps/web/app/modules/Dashboard/Dashboard.page.tsx
Labels: review me :eyes:

#225 fix: saving options for the question
  apps/api/src/lessons/adminLessonItems.service.ts
  apps/api/src/lessons/repositories/adminLessonItems.repository.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
Labels: bug :bug:, review me :eyes:

#224 feat: Tutor page
  apps/web/app/api/generated-api.ts
  apps/web/app/api/queries/useTutorCourses.ts
  apps/web/app/api/queries/useUserDetails.ts
  apps/web/app/assets/svgs/email.svg
  apps/web/app/assets/svgs/index.ts
  apps/web/app/assets/svgs/phone.svg
  apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
  apps/web/app/modules/Dashboard/Courses/CardCourseList.tsx
  apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
  apps/web/app/modules/Dashboard/Courses/StudentCoursesCarousel.tsx
  apps/web/app/modules/Dashboard/Dashboard.page.tsx
  apps/web/app/modules/Tutor/Tutor.page.tsx
  apps/web/app/modules/Tutor/TutorPageBreadcrumbs.tsx
  apps/web/routes.ts
  apps/web/tailwind.config.ts
  apps/web/vite.config.ts
Labels: review me :eyes:

#226 feat: check roles guard on endpoints
  apps/api/src/auth/api/auth.controller.ts
  apps/api/src/categories/api/categories.controller.ts
  apps/api/src/courses/api/courses.controller.ts
  apps/api/src/lessons/api/lessons.controller.ts
  apps/api/src/questions/api/questions.controller.ts
  apps/api/src/stripe/api/stripe.controller.ts
  apps/api/src/studentCompletedLessonItem/api/studentCompletedLessonItems.controller.ts
  apps/api/src/swagger/api-schema.json
  apps/api/src/users/__tests__/user.controller.e2e-spec.ts
  apps/api/src/users/api/users.controller.ts
  apps/api/test/factory/user.factory.ts
  apps/web/app/api/generated-api.ts
Labels: review me :eyes:

#220 feat: LC-330 limited admin panel for tutor
  apps/web/app/Guards/RouteGuard.tsx
  apps/web/app/Guards/__tests__/RouteGuard.test.tsx
  apps/web/app/Guards/__tests__/checkRouteAccess.test.ts
  apps/web/app/config/__tests__/navigationConfig.test.ts
  apps/web/app/config/navigationConfig.ts
  apps/web/app/config/routeAccessConfig.ts
  apps/web/app/config/userRoles.ts
  apps/web/app/hooks/useUserRole.ts
  apps/web/app/modules/Admin/Admin.layout.tsx
  apps/web/app/modules/Courses/Categories/Categories.page.tsx
  apps/web/app/modules/Courses/LessonItems/EditLessonItem.page.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItems.layout.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsAddText.page.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsAddVideo.page.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsButton.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsContext.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/LessonItemForm.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/LessonItemFormFile.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/LessonItemFormInput.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/LessonItemFormTextarea.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/RenderDialogForm.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/types.ts
  apps/web/app/modules/Courses/LessonItems/LessonItemsForms/zodFormType.ts
  apps/web/app/modules/Courses/LessonItems/LessonItemsTable/LessonItemsTable.tsx
  apps/web/app/modules/Courses/LessonItems/LessonItemsTable/columns.tsx
  apps/web/app/modules/Courses/LessonItems/LessonTableOptionButtons/TableButtonDelete.tsx
  apps/web/app/modules/Courses/LessonItems/LessonTableOptionButtons/TableButtonEdit.tsx
  apps/web/app/modules/Courses/LessonItems/LessonTableOptionButtons/TableButtonPreview.tsx
  apps/web/app/modules/Courses/LessonItems/LessonTableOptionButtons/TableOptionButtons.tsx
  apps/web/app/modules/Courses/LessonItems/UploadLessonVideo/UploadFile.tsx
  apps/web/app/modules/Courses/LessonItems/UploadLessonVideo/UploadFromInternet.tsx
  apps/web/app/modules/Courses/Lessons/Lessons.page.tsx
  apps/web/app/modules/Dashboard/Dashboard.layout.tsx
  apps/web/app/modules/Dashboard/Dashboard.page.tsx
  apps/web/app/modules/Dashboard/DashboardNavigation/DashboardNavigation.tsx
  apps/web/app/modules/Dashboard/DashboardNavigation/MenuItem.tsx
  apps/web/app/modules/Dashboard/DashboardNavigation/MenuItemLink.tsx
  apps/web/app/modules/Dashboard/hooks/useAuthorizedMenuItems.ts
  apps/web/app/modules/Landing/About.page.tsx
  apps/web/app/modules/Landing/Landing.layout.tsx
  apps/web/app/modules/Landing/Landing.page.tsx
  apps/web/app/modules/Landing/landingStore.ts
  apps/web/app/modules/Users/Users.page.tsx
  apps/web/routes.ts
Labels: review me :eyes:

#215 chore: update readme
  README.md
  apps/api/.env.example
Labels: review me :eyes:

#227 feat: update teachers bio
  README.md
  apps/api/src/auth/api/auth.controller.ts
  apps/api/src/categories/api/categories.controller.ts
  apps/api/src/courses/api/courses.controller.ts
  apps/api/src/seed.ts
  apps/api/src/studentCompletedLessonItem/api/studentCompletedLessonItems.controller.ts
  apps/api/src/swagger/api-schema.json
  apps/api/src/users/__tests__/user.controller.e2e-spec.ts
  apps/api/src/users/api/users.controller.ts
  apps/api/src/users/schemas/update-user.schema.ts
  apps/api/src/users/users.service.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/index.ts
  apps/web/app/api/mutations/useUpsertUserDetails.ts
  apps/web/app/api/queries/useUserDetails.ts
  apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
  apps/web/app/modules/Dashboard/Settings/forms/UserDetailsForm.tsx
Labels: merge me :green_heart:

#230 fix: LC-346 course/lesson image display
  apps/api/src/courses/courses.service.ts
  apps/api/src/courses/schemas/showCourseCommon.schema.ts
  apps/api/src/courses/schemas/updateCourse.schema.ts
  apps/api/src/file/api/s3.controller.ts
  apps/api/src/file/s3.service.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useDeleteFile.ts
  apps/web/app/modules/Admin/Courses/Course.page.tsx
  apps/web/app/modules/Admin/Courses/CreateNewCourse.page.tsx
  apps/web/app/modules/Admin/Lessons/CreateNewLesson.page.tsx
  apps/web/app/modules/Admin/Lessons/Lesson.page.tsx
Labels: merge me :green_heart:

#231 fix: LC-345 create without image
  apps/api/src/courses/courses.service.ts
  apps/api/src/courses/schemas/showCourseCommon.schema.ts
  apps/api/src/lessons/adminLessons.service.ts
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/lessons/schemas/lesson.schema.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/assets/placeholders/card-placeholder.jpg
  apps/web/app/modules/Admin/Courses/Course.page.tsx
  apps/web/app/modules/Admin/Courses/CreateNewCourse.page.tsx
  apps/web/app/modules/Admin/Courses/LessonAssigner/LessonCard.tsx
  apps/web/app/modules/Admin/Lessons/CreateNewLesson.page.tsx
  apps/web/app/modules/Admin/Lessons/Lesson.page.tsx
  apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
  apps/web/app/modules/Courses/CourseView/LessonCard.tsx
  apps/web/app/modules/Courses/Lesson/Overview.tsx
  apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
  apps/web/app/modules/Dashboard/Courses/TableCourseList.tsx
Labels: merge me :green_heart:

#180 test: LC-280 stripe tests
  .github/workflows/nighty-playwright.yml
  apps/api/src/e2e-data-seeds.ts
  apps/api/src/nice-data-seeds.ts
  apps/api/src/seed-helpers.ts
  apps/api/src/seed.ts
  apps/api/src/utils/types/test-types.ts
  apps/web/.gitignore
  apps/web/e2e/tests/get-course.spec.ts
  apps/web/e2e/tests/login.spec.ts
  apps/web/e2e/tests/register.spec.ts
  apps/web/playwright.config.ts
Labels: merge me :green_heart:

#232 feat: 361 allow to mark lessons in course as free
  apps/api/.eslintrc.js
  apps/api/package.json
  apps/api/src/courses/courses.service.ts
  apps/api/src/courses/schemas/course.schema.ts
  apps/api/src/courses/schemas/showCourseCommon.schema.ts
  apps/api/src/e2e-data-seeds.ts
  apps/api/src/lessons/adminLessons.service.ts
  apps/api/src/lessons/api/lessons.controller.ts
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/lessons/repositories/adminLessons.repository.ts
  apps/api/src/lessons/repositories/lessons.repository.ts
  apps/api/src/lessons/schemas/lesson.schema.ts
  apps/api/src/nice-data-seeds.ts
  apps/api/src/questions/questions.service.ts
  apps/api/src/seed-helpers.ts
  apps/api/src/storage/migrations/0008_add_is_free_to_course_lessons.sql
  apps/api/src/storage/migrations/meta/0008_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useToggleLessonAsFree.ts
  apps/web/app/api/mutations/admin/useUpdateLesson.ts
  apps/web/app/api/queries/useAvailableLessons.ts
  apps/web/app/assets/svgs/free-right.svg
  apps/web/app/assets/svgs/index.ts
  apps/web/app/components/CardBadge.tsx
  apps/web/app/components/RichText/Viever.tsx
  apps/web/app/components/ui/toaster.tsx
  apps/web/app/modules/Admin/Courses/LessonAssigner/LessonAssigner.tsx
  apps/web/app/modules/Admin/Courses/LessonAssigner/LessonCard.tsx
  apps/web/app/modules/Admin/Lessons/LessonDetails.tsx
  apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
  apps/web/app/modules/Courses/CourseView/CourseViewMainCard.tsx
  apps/web/app/modules/Courses/CourseView/LessonCard.tsx
  apps/web/app/modules/Courses/CourseView/LessonsList.tsx
  apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
  apps/web/app/modules/Courses/Lesson/Overview.tsx
  apps/web/app/modules/Dashboard/Courses/CardCourseList.tsx
  apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
  apps/web/app/modules/Dashboard/Courses/StudentCoursesCarousel.tsx
  apps/web/app/modules/Dashboard/Dashboard.page.tsx
  apps/web/app/modules/Tutor/Tutor.page.tsx
  pnpm-lock.yaml
Labels: merge me :green_heart:, review me :eyes:

#233 feat: LC-368 stats backend
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/auth/api/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/common/guards/refresh-token.guard.ts
  apps/api/src/common/types.ts
  apps/api/src/events/course/course-activity.event.ts
  apps/api/src/events/events.module.ts
  apps/api/src/events/index.ts
  apps/api/src/events/lesson/lesson-completed.event.ts
  apps/api/src/events/quiz/quiz-completed.event.ts
  apps/api/src/events/user/user-activity.event.ts
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/statistics/api/statistics.controller.ts
  apps/api/src/statistics/handlers/statistics.handler.ts
  apps/api/src/statistics/repositories/statistics.repository.ts
  apps/api/src/statistics/schemas/userStats.schema.ts
  apps/api/src/statistics/statistics.module.ts
  apps/api/src/statistics/statistics.service.ts
  apps/api/src/storage/migrations/0009_create_statistics.sql
  apps/api/src/storage/migrations/meta/0009_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  pnpm-lock.yaml
Labels: review me :eyes:

#235 feat: optimize video player import to use lazy loading in Video component
  apps/web/app/modules/Courses/Lesson/LessonItems/File/Video.tsx
Labels: review me :eyes:

#236 feat: implement LoginFixture for streamlined login/logout in e2e tests
  .prettierignore
  apps/web/e2e/auth.setup.ts
  apps/web/e2e/fixture/auth.fixture.ts
  apps/web/e2e/tests/get-course.spec.ts
  apps/web/e2e/tests/login.spec.ts
  apps/web/e2e/tests/register.spec.ts
  apps/web/playwright.config.ts
Labels: review me :eyes:

#237 test: add E2E quiz lesson seed and update test implementations for course enrollment and payment validation
  apps/api/src/e2e-data-seeds.ts
  apps/web/e2e/tests/course.spec.ts
  apps/web/e2e/tests/get-course.spec.ts
Labels: review me :eyes:

#186 chore: run e2e tests during deployment
  .github/workflows/deploy-api-production.yml
  .github/workflows/deploy-webapp-production.yml
  .github/workflows/nighty-playwright.yml
  .github/workflows/playwright-tests.yml
  apps/web/playwright.config.ts
Labels: review me :eyes:

#239 fix: enhance quiz answer checks in e2e tests to verify input state and visibility of missing answers
  apps/web/e2e/tests/course.spec.ts
Labels: review me :eyes:

#238 feat: 321 completed lesson improvements
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/lessons/repositories/lessons.repository.ts
  apps/api/src/lessons/schemas/lessonItem.schema.ts
  apps/api/src/questions/questions.module.ts
  apps/api/src/questions/questions.repository.ts
  apps/api/src/questions/questions.service.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/modules/Courses/Lesson/Breadcrumb.tsx
  apps/web/app/modules/Courses/Lesson/Lesson.layout.tsx
  apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/File/File.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/File/Presentation.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/File/Video.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/FillInTheBlanks.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/FillInTheBlanksDnd.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/LessonItem.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/LessonItemStore.ts
  apps/web/app/modules/Courses/Lesson/LessonItems/LessonItems.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/Question/Question.tsx
  apps/web/app/modules/Courses/Lesson/Overview.tsx
  apps/web/app/modules/Courses/Lesson/Summary/SingleLessonSummary.tsx
  apps/web/app/modules/Courses/Lesson/Summary/index.tsx
  apps/web/app/modules/Courses/Lesson/utils.ts
  apps/web/app/modules/Dashboard/Dashboard.layout.tsx
  apps/web/app/utils/handleCompletionForMediaLesson.tsx
  apps/web/routes.ts
Labels: merge me :green_heart:

#245 feat: integrate Sentry for error tracking and performance monitoring in web app
  .github/workflows/deploy-webapp-production.yml
  .github/workflows/deploy-webapp-staging.yml
  apps/web/.env.example
  apps/web/app/entry.client.tsx
  apps/web/package.json
  apps/web/vite.config.ts
  pnpm-lock.yaml
Labels: review me :eyes:

#246 fix: simplify layout in Statistics components
  apps/web/app/modules/Statistics/Statistics.page.tsx
  apps/web/app/modules/Statistics/components/AvgPercentScoreChart.tsx
  apps/web/app/modules/Statistics/components/ContinueLearningCard.tsx
  apps/web/app/modules/Statistics/components/ProfileWithCalendar.tsx
  apps/web/app/modules/Statistics/components/RatesChart.tsx
Labels: merge me :green_heart:

#247 feat: change string variables to constants
  apps/api/src/lessons/lessons.service.ts
  apps/api/src/lessons/repositories/lessons.repository.ts
  apps/api/src/seed-helpers.ts
  apps/api/src/statistics/handlers/statistics.handler.ts
  apps/api/src/statistics/repositories/statistics.repository.ts
  apps/api/src/statistics/statistics.service.ts
Labels: review me :eyes:

#249 fix: playwright workflow
  .github/workflows/playwright-tests.yml
Labels: review me :eyes:

#251 fix: Statistics page
  apps/api/src/storage/migrations/meta/0010_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/web/app/modules/Statistics/Statistics.page.tsx
  apps/web/app/modules/Statistics/components/ContinueLearningCard.tsx
  apps/web/app/modules/Statistics/components/ProfileWithCalendar.tsx
  pnpm-lock.yaml
Labels: review me :eyes:

#250 fix: Pages Layout and Dnd Blank and Word appearance
  apps/web/app/components/PageWrapper/PageWrapper.tsx
  apps/web/app/components/PageWrapper/index.ts
  apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
  apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DndBlank.tsx
  apps/web/app/modules/Courses/Lesson/LessonItems/FillInTheBlanks/dnd/DraggableWord.tsx
  apps/web/app/modules/Dashboard/Dashboard.layout.tsx
  apps/web/app/modules/Dashboard/Dashboard.page.tsx
  apps/web/app/modules/Dashboard/Settings/Settings.layout.tsx
  apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
  apps/web/app/modules/Statistics/Statistics.page.tsx
  apps/web/package.json
  apps/web/routes.ts
  pnpm-lock.yaml
Labels: merge me :green_heart:

#253 feat: add pricing and status view
  apps/web/app/components/FileUploadInput/ImageUploadInput.tsx
  apps/web/app/modules/Admin/AddCourse/AddCourse.tsx
  apps/web/app/modules/Admin/EditCourse/CoursePricing/CoursePricing.tsx
  apps/web/app/modules/Admin/EditCourse/CoursePricing/hooks/useCoursePricingForm.ts
  apps/web/app/modules/Admin/EditCourse/CoursePricing/validators/coursePricingFormSchema.ts
  apps/web/app/modules/Admin/EditCourse/CourseSettings/CourseSettings.tsx
  apps/web/app/modules/Admin/EditCourse/CourseStatus/CourseStatus.tsx
  apps/web/app/modules/Admin/EditCourse/CourseStatus/hooks/useCourseStatusForm.ts
  apps/web/app/modules/Admin/EditCourse/CourseStatus/validators/courseStatusFormSchema.ts
  apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
  apps/web/package.json
  pnpm-lock.yaml
Labels: merge me :green_heart:

#252 fix: playwright workflow
  .github/workflows/playwright-tests.yml
  apps/web/app/modules/Global/Providers.tsx
  apps/web/e2e/tests/course.spec.ts
  apps/web/package.json
  apps/web/vite.config.ts
  pnpm-lock.yaml
Labels: review me :eyes:

#255 fix: enable manual triggering for Playwright tests workflow
  .github/workflows/playwright-tests.yml
Labels: review me :eyes:

#261 chore: replace Playwright tests workflow reference and add production…
  .github/workflows/deploy-api-production.yml
  .github/workflows/deploy-webapp-production.yml
  .github/workflows/playwright-tests-production.yml
  .github/workflows/playwright-tests-staging.yml
Labels: review me :eyes:

#262 chore: update deploy API workflow to trigger on completion of web app…
  .github/workflows/deploy-api-production.yml
Labels: merge me :green_heart:

#257 feat: add most popular courses statistics
  apps/api/src/statistics/api/statistics.controller.ts
  apps/api/src/statistics/repositories/statistics.repository.ts
  apps/api/src/statistics/schemas/userStats.schema.ts
  apps/api/src/statistics/statistics.controller.ts
  apps/api/src/statistics/statistics.module.ts
  apps/api/src/statistics/statistics.service.ts
  apps/api/src/storage/migrations/0012_create_materialized_view_course_statistics_per_teacher.sql
  apps/api/src/storage/migrations/meta/0012_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/queries/useUserStatistics.ts
Labels: review me :eyes:

#258 feat: courses completion for teacher statistics
  apps/api/src/statistics/repositories/statistics.repository.ts
  apps/api/src/statistics/schemas/userStats.schema.ts
  apps/api/src/statistics/statistics.service.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
Labels: merge me :green_heart:

#264 fix: remove sidebar from splashscreen
  apps/web/app/modules/Admin/Admin.layout.tsx
  apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
  apps/web/app/modules/Admin/EditCourse/compontents/NavigationTabs.tsx
Labels: review me :eyes:
