Repository Selleo/mentingo, pull requests merged in 2025-10, with the labels that each got.

#705 feat: create embed lesson type
  apps/api/src/chapter/repositories/adminChapter.repository.ts
  apps/api/src/lesson/lesson.controller.ts
  apps/api/src/lesson/lesson.schema.ts
  apps/api/src/lesson/lesson.type.ts
  apps/api/src/lesson/repositories/adminLesson.repository.ts
  apps/api/src/lesson/repositories/lesson.repository.ts
  apps/api/src/lesson/services/adminLesson.service.ts
  apps/api/src/lesson/services/lesson.service.ts
  apps/api/src/storage/migrations/0015_change_option_text_to_text_type.sql
  apps/api/src/storage/migrations/0039_add_lesson_resources_table.sql
  apps/api/src/storage/migrations/meta/0039_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/studentLessonProgress/studentLessonProgress.controller.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useCreateEmbedLesson.ts
  apps/web/app/api/mutations/admin/useUpdateEmbedLesson.ts
  apps/web/app/assets/svgs/lesson-types/embed.svg
  apps/web/app/assets/svgs/lesson-types/index.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Admin/EditCourse/CourseLessons/CourseLessons.helpers.ts
  apps/web/app/modules/Admin/EditCourse/CourseLessons/CourseLessons.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/EmbedLessonForm.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/components/EmbedLessonResourceCard.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/constants.ts
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/hooks/useEmbedLessonForm.ts
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/schemas/embedLessonForm.schema.ts
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/EmbedLessonForm/schemas/embedLessonResource.schema.ts
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/components/SelectLessonType.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/components/LessonCardList.tsx
  apps/web/app/modules/Admin/EditCourse/EditCourse.types.ts
  apps/web/app/modules/Admin/components/DeleteConfirmationModal.tsx
  apps/web/app/modules/Courses/CourseView/lessonTypes.ts
  apps/web/app/modules/Courses/Lesson/EmbedLesson/EmbedFrame.tsx
  apps/web/app/modules/Courses/Lesson/EmbedLesson/EmbedLesson.tsx
  apps/web/app/modules/Courses/Lesson/LessonContent.tsx
Labels: review me :eyes:

#706 fix: sso redirect on login to use current url
  apps/web/app/modules/Auth/components/SocialLogin.tsx
Labels: review me :eyes:

#708 feat(648): Implemented Env Config Page to edit env's via platform
  .github/workflows/pr-backend-ci.yml
  apps/api/.env.example
  apps/api/src/ai/services/ai.service.ts
  apps/api/src/ai/services/chat.service.ts
  apps/api/src/ai/services/prompt.service.ts
  apps/api/src/ai/services/rag.service.ts
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/strategy/google.strategy.ts
  apps/api/src/auth/strategy/microsoft.strategy.ts
  apps/api/src/bunny/bunnyStream.service.ts
  apps/api/src/common/guards/google-oauth.guard.ts
  apps/api/src/common/guards/microsoft-oauth.guard.ts
  apps/api/src/env/env.config.ts
  apps/api/src/env/env.controller.ts
  apps/api/src/env/env.module.ts
  apps/api/src/env/env.schema.ts
  apps/api/src/env/repositories/env.repository.ts
  apps/api/src/env/services/env.service.ts
  apps/api/src/seed/seed-helpers.ts
  apps/api/src/storage/migrations/0040_added_secrets_table.sql
  apps/api/src/storage/migrations/meta/0040_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/stripe/stripe.service.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useBulkUpsertSecret.ts
  apps/web/app/api/queries/admin/useSecret.ts
  apps/web/app/api/queries/useSSOEnabled.ts
  apps/web/app/config/routeAccessConfig.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Admin/Envs/Envs.constants.ts
  apps/web/app/modules/Admin/Envs/Envs.page.tsx
  apps/web/app/modules/Auth/Login.page.tsx
  apps/web/app/modules/Auth/Register.page.tsx
  apps/web/routes.ts
Labels: new feedback :balloon:

#701 fix: editor initial height
  apps/web/app/components/RichText/Editor.tsx
Labels: review me :eyes:

#716 test: verify quiz access rules for attempts and cooldown
  apps/api/.eslintrc.js
  apps/api/src/utils/__tests__/isQuizAccessAllowed.spec.ts
Labels: review me :eyes:

#720 test: add config validator unit tests
  apps/api/src/utils/__tests__/configValidator.spec.ts
Labels: review me :eyes:

#729 fix: add checks if category already exists and return a meaningful error
  apps/api/src/category/category.service.ts
Labels: review me :eyes:

#714 feat(710): added settings to allow invite only registration
  apps/api/src/ai/services/rag.service.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/settings/constants/settings.constants.ts
  apps/api/src/settings/schemas/settings.schema.ts
  apps/api/src/settings/settings.controller.ts
  apps/api/src/settings/settings.service.ts
  apps/api/src/storage/migrations/0041_added_invite_only_registration_setting.sql
  apps/api/src/storage/migrations/meta/0041_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useUpdateInviteOnlyRegistration.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Auth/CreateNewPassword.page.tsx
  apps/web/app/modules/Auth/Login.page.tsx
  apps/web/app/modules/Auth/Register.page.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/InviteOnlyRegistration.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/OrganizationTabContent.tsx
  apps/web/app/modules/Dashboard/Settings/types.ts
Labels: merge me :green_heart:

#739 fix: learn deploy workflow missing env
  .github/workflows/deploy-learn-production.yml
Labels: review me :eyes:
