Repository Selleo/mentingo, pull requests merged in 2025-07, with the labels that each got.

#475 refactor: Update README.md
  README.md
Labels: review me :eyes:

#484 refactor(SCS-474): rename teacher to content creator and migrate roles in database
  apps/api/src/chapter/chapter.controller.ts
  apps/api/src/courses/__tests__/course.controller.e2e-spec.ts
  apps/api/src/courses/course.controller.ts
  apps/api/src/courses/course.service.ts
  apps/api/src/courses/schemas/course.schema.ts
  apps/api/src/file/file.controller.ts
  apps/api/src/lesson/lesson.controller.ts
  apps/api/src/scorm/scorm.controller.ts
  apps/api/src/seed/seed-prod.ts
  apps/api/src/seed/seed.ts
  apps/api/src/seed/users-seed.ts
  apps/api/src/statistics/schemas/userStats.schema.ts
  apps/api/src/statistics/statistics.controller.ts
  apps/api/src/statistics/statistics.service.ts
  apps/api/src/storage/migrations/0015_change_user_role_from_teacher_to_content_creator.sql
  apps/api/src/storage/migrations/meta/0015_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/studentLessonProgress/studentLessonProgress.service.ts
  apps/api/src/swagger/api-schema.json
  apps/api/src/user/schemas/userRoles.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.service.ts
  apps/web/app/Guards/__tests__/RouteGuard.test.tsx
  apps/web/app/Guards/__tests__/checkRouteAccess.test.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/api/queries/index.ts
  apps/web/app/api/queries/useContentCreatorCourses.ts
  apps/web/app/api/queries/useContentCreatorStatistics.ts
  apps/web/app/api/queries/useTeacherStatistics.ts
  apps/web/app/config/__tests__/navigationConfig.test.ts
  apps/web/app/config/navigationConfig.ts
  apps/web/app/config/routeAccessConfig.ts
  apps/web/app/config/userRoles.ts
  apps/web/app/hooks/useUserRole.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Admin/Admin.layout.tsx
  apps/web/app/modules/Admin/Users/CreateNewUser.page.tsx
  apps/web/app/modules/Admin/Users/UserInfo.tsx
  apps/web/app/modules/Admin/Users/Users.page.tsx
  apps/web/app/modules/ContentCreator/ContentCreator.page.tsx
  apps/web/app/modules/ContentCreator/ContentCreatorPageBreadcrumbs.tsx
  apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
  apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseViewSidebar.tsx
  apps/web/app/modules/Courses/CourseView/MoreCoursesByAuthor.tsx
  apps/web/app/modules/Courses/Courses.page.tsx
  apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
  apps/web/app/modules/Statistics/Admin/AdminStatistics.tsx
  apps/web/app/modules/Statistics/Admin/components/FiveMostPopularCoursesChart.tsx
  apps/web/app/modules/Statistics/Statistics.page.tsx
  apps/web/e2e/auth.setup.ts
  apps/web/e2e/tests/admin/admin-navigation.spec.ts
  apps/web/e2e/tests/admin/settings.spec.ts
  apps/web/e2e/tests/content-creator/content-creator-navigation.spec.ts
  apps/web/e2e/tests/content-creator/edit-course.spec.ts
  apps/web/e2e/tests/content-creator/settings.spec.ts
  apps/web/e2e/tests/student/student-navigation.spec.ts
  apps/web/playwright.config.ts
  apps/web/routes.ts
Labels: merge me :green_heart:

#485 fix: add queryclient to mutation for nagivgating user correctly
  apps/web/app/api/mutations/useLoginUser.ts
Labels: merge me :green_heart:

#494 docs(SCS): update README.md with current available accounts
  README.md
Labels: review me :eyes:

#498 refactor(SCS): change h-* w-* classes to size-* when the element is square
  apps/web/app/components/Navigation/Navigation.tsx
  apps/web/app/components/Navigation/NavigationFooter.tsx
  apps/web/app/components/RichText/toolbar/EditorToolbar.tsx
  apps/web/app/components/TableSortButton/TableSortButton.tsx
  apps/web/app/components/ThemeToggle/ThemeToggle.tsx
  apps/web/app/components/VideoPlayer/VideoPlayer.tsx
  apps/web/app/components/ui/avatar.tsx
  apps/web/app/components/ui/breadcrumb.tsx
  apps/web/app/components/ui/button.tsx
  apps/web/app/components/ui/calendar.tsx
  apps/web/app/components/ui/carousel.tsx
  apps/web/app/components/ui/chart.tsx
  apps/web/app/components/ui/checkbox.tsx
  apps/web/app/components/ui/dialog.tsx
  apps/web/app/components/ui/dropdown-menu.tsx
  apps/web/app/components/ui/navigation-menu.tsx
  apps/web/app/components/ui/radio-group.tsx
  apps/web/app/components/ui/select.tsx
  apps/web/app/components/ui/separator.tsx
  apps/web/app/components/ui/sheet.tsx
  apps/web/app/components/ui/toast.tsx
  apps/web/app/components/ui/toaster.tsx
  apps/web/app/modules/Admin/AddCourse/components/Breadcrumb.tsx
  apps/web/app/modules/Admin/Categories/Categories.page.tsx
  apps/web/app/modules/Admin/Courses/Courses.page.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/AnswerSelectQuestion.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/MatchWordsQuestion.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/PhotoQuestion.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionSelector.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/QuestionTitle.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/ScaleQuestion.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/NewLesson/QuizLessonForm/components/TrueOrFalseQuestion.tsx
  apps/web/app/modules/Admin/EditCourse/CourseLessons/components/ChaptersList.tsx
  apps/web/app/modules/Admin/EditCourse/CoursePricing/CoursePricing.tsx
  apps/web/app/modules/Admin/EditCourse/CourseStatus/CourseStatus.tsx
  apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
  apps/web/app/modules/Admin/EditCourse/compontents/CourseCardPreview.tsx
  apps/web/app/modules/Admin/Groups/Groups.page.tsx
  apps/web/app/modules/Admin/Scorm/components/Progress.tsx
  apps/web/app/modules/Admin/Scorm/components/ScormUploadStep.tsx
  apps/web/app/modules/Admin/Scorm/components/StepWrapper.tsx
  apps/web/app/modules/Admin/Users/Users.page.tsx
  apps/web/app/modules/Admin/components/DeleteConfirmationModal.tsx
  apps/web/app/modules/Admin/components/LeaveConfirmationModal.tsx
  apps/web/app/modules/Courses/CourseView/CourseChapter.tsx
  apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseViewSidebar.tsx
  apps/web/app/modules/Courses/Lesson/Question/MultipleChoice/MultiSelect.tsx
  apps/web/app/modules/Courses/Lesson/Question/SingleChoice/SingleSelect.tsx
  apps/web/app/modules/Courses/components/CourseCard.tsx
  apps/web/app/modules/Courses/components/CourseCardButton.tsx
  apps/web/app/modules/Dashboard/Courses/CourseCard.tsx
  apps/web/app/modules/Dashboard/Courses/CourseCardButton.tsx
  apps/web/app/modules/Profile/Profile.page.tsx
  apps/web/app/modules/Statistics/Admin/components/EnrollmentChart.tsx
  apps/web/app/modules/Statistics/Admin/components/FiveMostPopularCoursesChart.tsx
  apps/web/app/modules/Statistics/Client/components/ChapterCard.tsx
  apps/web/app/modules/Statistics/Client/components/RatesChart.tsx
  apps/web/app/modules/common/Loader/Loader.tsx
  apps/web/app/modules/common/SearchFilter/SearchFilter.tsx
Labels: review me :eyes:

#508 refactor(SCS-486): clean up student and content creator profile according to design
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Profile/Profile.page.tsx
  apps/web/app/modules/Profile/components/ProfileCard.tsx
  apps/web/app/modules/Profile/components/index.ts
Labels: merge me :green_heart:, new feedback :balloon:

#510 fix: Update Profile URL and Navigation Text
  .github/pull_request_template.md
  apps/api/.eslintrc.js
  apps/api/src/swagger/api-schema.json
  apps/api/test/create-e2e-test.ts
  apps/api/test/create-unit-test.ts
  apps/api/test/jest-e2e-setup.ts
  apps/api/test/jest-e2e.json
  apps/api/test/test-database.ts
  apps/web/app/api/generated-api.ts
  apps/web/e2e/tests/admin/admin-navigation.spec.ts
  apps/web/e2e/tests/admin/settings.spec.ts
  apps/web/e2e/tests/content-creator/content-creator-navigation.spec.ts
  apps/web/e2e/tests/content-creator/settings.spec.ts
  apps/web/e2e/tests/student/student-navigation.spec.ts
Labels: review me :eyes:

#493 fix(SCS-490): fixed secondary styling for share button
  apps/web/app/modules/Courses/CourseView/CourseViewSidebar/CourseProgress.tsx
Labels: merge me :green_heart:

#504 feat(SCS): added msw handler for profile page tests
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Profile/Profile.page.test.tsx
  apps/web/app/utils/mocks/data/userDetails.ts
  apps/web/app/utils/mocks/handlers/index.ts
  apps/web/app/utils/mocks/handlers/userDetails.ts
Labels: merge me :green_heart:

#497 feat(SCS-462): Implement ability to change UI language
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Dashboard/Settings/Language/LanguageProvider.tsx
  apps/web/app/modules/Dashboard/Settings/Language/LanguageStore.ts
  apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
  apps/web/app/modules/Dashboard/Settings/components/LanguageSelect.tsx
  apps/web/app/modules/Global/Providers.tsx
Labels: merge me :green_heart:

#495 feat(SCS-473): Add breadcrumbs to each view
  apps/web/app/components/PageWrapper/PageWrapper.tsx
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Admin/Categories/Category.page.tsx
  apps/web/app/modules/Admin/Categories/CreateNewCategory.page.tsx
  apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
  apps/web/app/modules/Admin/Groups/CreateGroup.page.tsx
  apps/web/app/modules/Admin/Groups/EditGroup.page.tsx
  apps/web/app/modules/Admin/Users/CreateNewUser.page.tsx
  apps/web/app/modules/Admin/Users/User.page.tsx
  apps/web/app/modules/Courses/CourseView/CourseView.page.tsx
  apps/web/app/modules/Courses/Lesson/Lesson.page.tsx
Labels: merge me :green_heart:, new feedback :balloon:

#518 feat(SCS-471): add user profile update functionality
  apps/api/src/swagger/api-schema.json
  apps/api/src/user/schemas/updateUser.schema.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.service.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/index.ts
  apps/web/app/api/mutations/useUpdateUserProfile.ts
  apps/web/app/assets/svgs/edit.svg
  apps/web/app/assets/svgs/index.ts
  apps/web/app/assets/svgs/x.svg
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Profile/Profile.page.tsx
  apps/web/app/modules/Profile/components/EditModeActionButtons.tsx
  apps/web/app/modules/Profile/components/OwnerViewActionButtons.tsx
  apps/web/app/modules/Profile/components/ProfileActionButtons.tsx
  apps/web/app/modules/Profile/components/ProfileEditCard.tsx
  apps/web/app/modules/Profile/components/ProfileEditFieldRenderer.tsx
  apps/web/app/modules/Profile/components/VisitorViewActionButtons.tsx
  apps/web/app/modules/Profile/components/index.ts
  apps/web/app/utils/__tests__/filterChangedData.test.ts
  apps/web/app/utils/copyToClipboard.ts
  apps/web/app/utils/filterChangedData.ts
Labels: merge me :green_heart:

#515 feat(SCS-477): added group characteristics and implemented new design
  apps/api/src/category/category.service.ts
  apps/api/src/group/group.schema.ts
  apps/api/src/group/group.service.ts
  apps/api/src/storage/migrations/0016_rename_description_to_characteristic_in_groups_table.sql
  apps/api/src/storage/migrations/meta/0016_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/swagger/api-schema.json
  apps/web/app/api/generated-api.ts
  apps/web/app/assets/svgs/index.ts
  apps/web/app/assets/svgs/x-icon.svg
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Admin/Groups/CreateGroup.page.tsx
  apps/web/app/modules/Admin/Groups/EditGroup.page.tsx
  apps/web/app/modules/Admin/Groups/Groups.page.tsx
  apps/web/app/modules/Admin/Groups/components/CreateGroupCard.tsx
  apps/web/app/modules/Admin/Groups/components/GroupBreadcrumbs.tsx
  apps/web/app/modules/Admin/Groups/components/GroupBreadcrumbsButton.tsx
  apps/web/app/modules/Admin/Groups/components/GroupHeader.tsx
  apps/web/app/modules/Admin/Groups/components/RequiredTick.tsx
  apps/web/app/modules/Admin/Groups/group.utils.ts
  apps/web/app/modules/Admin/Groups/hooks/useGroupTable.tsx
Labels: merge me :green_heart:

#521 fix(SCS-500): Add roles and verifications to course editing
  .prettierrc.js
  apps/api/src/courses/course.controller.ts
  apps/api/src/courses/course.service.ts
  apps/web/app/modules/Admin/EditCourse/EditCourse.tsx
Labels: merge me :green_heart:, new feedback :balloon:

#537 feat(SCS-513): Limit account creation reminders to 3
  apps/api/src/auth/auth.service.ts
  apps/api/src/storage/migrations/0018_add_reminder_count_to_create_tokens.sql
  apps/api/src/storage/migrations/meta/0018_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/user/user.service.ts
Labels: merge me :green_heart:

#522 feat(SCS-464): implement avatar change
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/common/configuration/aws.ts
  apps/api/src/file/file.controller.ts
  apps/api/src/group/group.schema.ts
  apps/api/src/s3/s3.service.ts
  apps/api/src/storage/migrations/0019_add_avatar_refence_to_user.sql
  apps/api/src/storage/migrations/meta/0019_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/storage/schema/index.ts
  apps/api/src/swagger/api-schema.json
  apps/api/src/user/schemas/updateUser.schema.ts
  apps/api/src/user/schemas/user.schema.ts
  apps/api/src/user/user.controller.ts
  apps/api/src/user/user.module.ts
  apps/api/src/user/user.service.ts
  apps/api/src/utils/__tests__/validateMultipartPipe.spec.ts
  apps/api/src/utils/pipes/validateMultipartPipe.ts
  apps/api/test/factory/user.factory.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/useUpdateUserProfile.ts
  apps/web/app/components/FileUploadInput/ImageUploadInput.tsx
  apps/web/app/hooks/useHandleImageUpload.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Profile/Profile.page.tsx
  apps/web/app/modules/Profile/components/EditModeActionButtons.tsx
  apps/web/app/modules/Profile/components/ProfileActionButtons.tsx
  apps/web/app/modules/Profile/components/ProfileCard.tsx
  apps/web/app/modules/Profile/components/ProfileEditCard.tsx
  apps/web/app/modules/Profile/components/ProfileEditFieldRenderer.tsx
  apps/web/app/modules/Profile/types/index.ts
Labels: merge me :green_heart:

#520 feat(SCS-467): Enforce Strong Password Policy
  .tool-versions
  apps/api/src/auth/__tests__/auth.controller.e2e-spec.ts
  apps/api/src/auth/schemas/create-account.schema.ts
  apps/api/src/auth/schemas/create-password.schema.ts
  apps/api/src/auth/schemas/password.schema.ts
  apps/api/src/auth/schemas/reset-password.schema.ts
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/swagger/api-schema.json
  apps/api/src/user/__tests__/user.controller.e2e-spec.ts
  apps/api/src/user/schemas/changePassword.schema.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/components/PasswordStrengthBars.tsx
  apps/web/app/components/PasswordValidation/PasswordValidationDisplay.tsx
  apps/web/app/components/PasswordValidation/PasswordValidationRuleItem.tsx
  apps/web/app/components/ui/form-validation-error.tsx
  apps/web/app/hooks/usePasswordValidationRules.ts
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Auth/CreateNewPassword.page.tsx
  apps/web/app/modules/Auth/Register.page.test.tsx
  apps/web/app/modules/Auth/Register.page.tsx
  apps/web/app/modules/Auth/constants.ts
  apps/web/app/modules/Auth/utils.ts
  apps/web/app/modules/Dashboard/Settings/forms/ChangePasswordForm.tsx
  apps/web/app/modules/Dashboard/Settings/schema/password.schema.ts
  apps/web/e2e/tests/student/register.spec.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: merge me :green_heart:

#532 feat(SCS-459): implement google sso
  .github/workflows/pr-backend-ci.yml
  apps/api/.env.example
  apps/api/package.json
  apps/api/src/app.module.ts
  apps/api/src/auth/auth.controller.ts
  apps/api/src/auth/auth.module.ts
  apps/api/src/auth/auth.service.ts
  apps/api/src/auth/strategy/google.strategy.ts
  apps/api/src/auth/token.service.ts
  apps/api/src/common/guards/google-oauth.guard.ts
  apps/api/src/swagger/api-schema.json
  apps/api/src/utils/types/google-user.type.ts
  apps/web/.env.example
  apps/web/app/api/mutations/useLogoutUser.ts
  apps/web/app/assets/svgs/google.svg
  apps/web/app/assets/svgs/index.ts
  apps/web/app/components/Auth/GoogleOAuthButton.tsx
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Auth/Login.page.tsx
  apps/web/app/modules/Auth/Register.page.tsx
  apps/web/app/modules/Auth/components/SocialLogin.tsx
  apps/web/app/modules/Auth/components/index.ts
  apps/web/app/modules/Dashboard/UserDashboard.layout.tsx
  apps/web/app/modules/Dashboard/hooks/useSyncUserAfterProviderLogin.ts
  apps/web/app/modules/Profile/components/ProfileEditCard.tsx
  pnpm-lock.yaml
Labels: merge me :green_heart:

#561 chore(SCS-552): added forcePathStyle true to S3Service
  apps/api/src/s3/s3.service.ts
Labels: merge me :green_heart:

#567 feat(SCS-559): added e2e tests for profile page
  apps/api/src/auth/__tests__/auth.controller.e2e-spec.ts
  apps/api/src/auth/auth.service.ts
  apps/web/app/components/FileUploadInput/ImageUploadInput.tsx
  apps/web/app/locales/en/translation.json
  apps/web/app/modules/Profile/components/ProfileCard.tsx
  apps/web/app/modules/Profile/components/ProfileEditFieldRenderer.tsx
  apps/web/e2e/data/images/profile_icon_test.png
  apps/web/e2e/tests/admin/profile.spec.ts
  apps/web/e2e/tests/student/profile.spec.ts
Labels: merge me :green_heart:

#553 feat(SCS-517): Add setting to allow unregistered access
  apps/api/src/common/types.ts
  apps/api/src/seed/seed.ts
  apps/api/src/settings/__tests__/settings.controller.e2e-spec.ts
  apps/api/src/settings/constants/settings.constants.ts
  apps/api/src/settings/schemas/settings.schema.ts
  apps/api/src/settings/settings.controller.ts
  apps/api/src/settings/settings.service.ts
  apps/api/src/storage/migrations/0022_update_settings_with_unregistered_user_courses_accessibility.sql
  apps/api/src/storage/migrations/0025_update_settings_with_unregistered_user_courses_accessibility.sql
  apps/api/src/storage/migrations/meta/0025_snapshot.json
  apps/api/src/storage/migrations/meta/_journal.json
  apps/api/src/swagger/api-schema.json
  apps/api/src/utils/settings-type-guards.ts
  apps/api/test/factory/settings.factory.ts
  apps/web/app/api/generated-api.ts
  apps/web/app/api/mutations/admin/useUnregisteredUserCoursesAccessibility.ts
  apps/web/app/api/mutations/useChangeLanguage.ts
  apps/web/app/api/mutations/useCurrentLanguage.ts
  apps/web/app/api/queries/useGlobalSettings.ts
  apps/web/app/components/ui/hover-card.tsx
  apps/web/app/locales/en/translation.json
  apps/web/app/locales/pl/translation.json
  apps/web/app/modules/Courses/Courses.layout.tsx
  apps/web/app/modules/Courses/Courses.page.tsx
  apps/web/app/modules/Dashboard/Settings/Language/LanguageProvider.tsx
  apps/web/app/modules/Dashboard/Settings/Settings.page.tsx
  apps/web/app/modules/Dashboard/Settings/components/AccountTabContent.tsx
  apps/web/app/modules/Dashboard/Settings/components/LanguageSelect.tsx
  apps/web/app/modules/Dashboard/Settings/components/NotificationPreferences.tsx
  apps/web/app/modules/Dashboard/Settings/components/SettingItem.tsx
  apps/web/app/modules/Dashboard/Settings/components/SettingsNavigationTabs.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/CoursesAccessibilityPreferences.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/GlobalPreferences.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/OrganizationTabContent.tsx
  apps/web/app/modules/Dashboard/Settings/components/admin/Preferences.tsx
  apps/web/app/modules/Dashboard/Settings/forms/NotificationPreferencesForm.tsx
  apps/web/app/modules/Dashboard/Settings/types.ts
  apps/web/e2e/tests/admin/settings.spec.ts
  apps/web/package.json
  pnpm-lock.yaml
Labels: review me :eyes:
